name: Scan CloudFormation Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AWS Sustainability Scanner GitHub Action
        uses: aws-actions/sustainability-scanner@v1.3.1
  
